/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as SchemaDotjsonRouteImport } from './routes/schema[.]json'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as ApiV1ReportsRouteImport } from './routes/api/v1/reports'
import { Route as RSlugJsonRouteImport } from './routes/r.$slug.json'
import { Route as ApiPublicPipelineRunRouteImport } from './routes/api/public/pipeline/run'
import { Route as ApiV1ReportsIdRouteImport } from './routes/api/v1/reports.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaDotjsonRoute = SchemaDotjsonRouteImport.update({
  id: '/schema.json',
  path: '/schema.json',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReportsRoute = ApiV1ReportsRouteImport.update({
  id: '/api/v1/reports',
  path: '/api/v1/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugJsonRoute = RSlugJsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => RSlugRoute,
} as any)
const ApiPublicPipelineRunRoute = ApiPublicPipelineRunRouteImport.update({
  id: '/api/public/pipeline/run',
  path: '/api/public/pipeline/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReportsIdRoute = ApiV1ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1ReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/schema.json': typeof SchemaDotjsonRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/api/v1/reports': typeof ApiV1ReportsRouteWithChildren
  '/r/$slug/json': typeof RSlugJsonRoute
  '/api/public/pipeline/run': typeof ApiPublicPipelineRunRoute
  '/api/v1/reports/$id': typeof ApiV1ReportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/schema.json': typeof SchemaDotjsonRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/api/v1/reports': typeof ApiV1ReportsRouteWithChildren
  '/r/$slug/json': typeof RSlugJsonRoute
  '/api/public/pipeline/run': typeof ApiPublicPipelineRunRoute
  '/api/v1/reports/$id': typeof ApiV1ReportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/schema.json': typeof SchemaDotjsonRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/api/v1/reports': typeof ApiV1ReportsRouteWithChildren
  '/r/$slug/json': typeof RSlugJsonRoute
  '/api/public/pipeline/run': typeof ApiPublicPipelineRunRoute
  '/api/v1/reports/$id': typeof ApiV1ReportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/schema.json'
    | '/r/$slug'
    | '/api/v1/reports'
    | '/r/$slug/json'
    | '/api/public/pipeline/run'
    | '/api/v1/reports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/schema.json'
    | '/r/$slug'
    | '/api/v1/reports'
    | '/r/$slug/json'
    | '/api/public/pipeline/run'
    | '/api/v1/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/schema.json'
    | '/r/$slug'
    | '/api/v1/reports'
    | '/r/$slug/json'
    | '/api/public/pipeline/run'
    | '/api/v1/reports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SchemaDotjsonRoute: typeof SchemaDotjsonRoute
  RSlugRoute: typeof RSlugRouteWithChildren
  ApiV1ReportsRoute: typeof ApiV1ReportsRouteWithChildren
  ApiPublicPipelineRunRoute: typeof ApiPublicPipelineRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema.json': {
      id: '/schema.json'
      path: '/schema.json'
      fullPath: '/schema.json'
      preLoaderRoute: typeof SchemaDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports': {
      id: '/api/v1/reports'
      path: '/api/v1/reports'
      fullPath: '/api/v1/reports'
      preLoaderRoute: typeof ApiV1ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug/json': {
      id: '/r/$slug/json'
      path: '/json'
      fullPath: '/r/$slug/json'
      preLoaderRoute: typeof RSlugJsonRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/api/public/pipeline/run': {
      id: '/api/public/pipeline/run'
      path: '/api/public/pipeline/run'
      fullPath: '/api/public/pipeline/run'
      preLoaderRoute: typeof ApiPublicPipelineRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/$id': {
      id: '/api/v1/reports/$id'
      path: '/$id'
      fullPath: '/api/v1/reports/$id'
      preLoaderRoute: typeof ApiV1ReportsIdRouteImport
      parentRoute: typeof ApiV1ReportsRoute
    }
  }
}

interface RSlugRouteChildren {
  RSlugJsonRoute: typeof RSlugJsonRoute
}

const RSlugRouteChildren: RSlugRouteChildren = {
  RSlugJsonRoute: RSlugJsonRoute,
}

const RSlugRouteWithChildren = RSlugRoute._addFileChildren(RSlugRouteChildren)

interface ApiV1ReportsRouteChildren {
  ApiV1ReportsIdRoute: typeof ApiV1ReportsIdRoute
}

const ApiV1ReportsRouteChildren: ApiV1ReportsRouteChildren = {
  ApiV1ReportsIdRoute: ApiV1ReportsIdRoute,
}

const ApiV1ReportsRouteWithChildren = ApiV1ReportsRoute._addFileChildren(
  ApiV1ReportsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SchemaDotjsonRoute: SchemaDotjsonRoute,
  RSlugRoute: RSlugRouteWithChildren,
  ApiV1ReportsRoute: ApiV1ReportsRouteWithChildren,
  ApiPublicPipelineRunRoute: ApiPublicPipelineRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
